# Generated by Django 4.0 on 2022-01-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/course')),
                ('duration', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('total_views', models.IntegerField()),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Course_skills',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('skills', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
