# Generated by Django 4.0 on 2022-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_c_id_alter_course_skills_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='Beginners', max_length=30),
        ),
    ]
