# Generated by Django 4.0 on 2022-01-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='guided_project',
            field=models.BooleanField(default=False),
        ),
    ]
