# Generated by Django 4.0 on 2022-01-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='playlistid',
            field=models.URLField(default='PLsyeobzWxl7poL9JTVyndKe62ieoN-MZ3'),
            preserve_default=False,
        ),
    ]
