# Generated by Django 4.0 on 2022-01-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='playlistid',
            field=models.CharField(max_length=40),
        ),
    ]
