# Generated by Django 4.0 on 2022-01-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_course_no_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_skills',
            name='skills',
            field=models.CharField(max_length=100),
        ),
    ]
