# Generated by Django 4.0 on 2022-01-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='f_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
