# Generated by Django 4.0 on 2022-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_faculty_f_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='phone',
            field=models.CharField(default=9999999999, max_length=10),
            preserve_default=False,
        ),
    ]
