# Generated by Django 4.0 on 2022-01-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='media/student/default.jpg', upload_to='media/student'),
        ),
    ]
