# Generated by Django 4.0 on 2022-01-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
