# Generated by Django 4.0 on 2022-01-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_s_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
