# Generated by Django 4.0 on 2022-01-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_enrolls_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolls',
            name='watched',
            field=models.CharField(default='', max_length=500),
        ),
    ]
