# Generated by Django 4.0 on 2022-02-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_course_skills_skills'),
        ('student', '0006_enrolls_watched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utr_no', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='media/payment')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='payed',
            field=models.ManyToManyField(related_name='payed', through='student.Pays', to='course.Course'),
        ),
        migrations.AddField(
            model_name='pays',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AlterUniqueTogether(
            name='pays',
            unique_together={('s_id', 'c_id')},
        ),
    ]
