# Generated by Django 4.0 on 2022-02-09 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 9)),
        ),
        migrations.AddField(
            model_name='pays',
            name='time',
            field=models.TimeField(default=datetime.time(19, 36, 12, 223080)),
        ),
        migrations.AlterField(
            model_name='pays',
            name='image',
            field=models.ImageField(upload_to='payment'),
        ),
    ]
