# Generated by Django 4.0 on 2022-02-16 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_pays_date_pays_time_alter_pays_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 16)),
        ),
        migrations.AlterField(
            model_name='pays',
            name='time',
            field=models.TimeField(default=datetime.time(12, 6, 27, 360042)),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='student/default.jpg', upload_to='media/student'),
        ),
    ]
