# Generated by Django 4.0 on 2022-03-28 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_pays_date_alter_pays_time_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 28)),
        ),
        migrations.AlterField(
            model_name='pays',
            name='time',
            field=models.TimeField(default=datetime.time(14, 10, 56, 266619)),
        ),
    ]
