# Generated by Django 4.0 on 2022-04-27 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_pays_date_alter_pays_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='Verified', max_length=20),
        ),
        migrations.AlterField(
            model_name='pays',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
        migrations.AlterField(
            model_name='pays',
            name='time',
            field=models.TimeField(default=datetime.time(14, 52, 15, 120508)),
        ),
    ]
