# Generated by Django 4.0 on 2022-04-27 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_status_alter_pays_date_alter_pays_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='time',
            field=models.TimeField(default=datetime.time(14, 52, 53, 22238)),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
