# Generated by Django 4.0 on 2022-01-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_alter_institute_i_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='image',
            field=models.ImageField(upload_to='institute'),
        ),
    ]
