# Generated by Django 4.0 on 2022-01-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_alter_institute_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='ac_name',
            field=models.CharField(default='Principal, JNNCE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institute',
            name='ac_no',
            field=models.CharField(default='6322201000004', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institute',
            name='b_address',
            field=models.CharField(default='JNNCE CAMPUS BRANCH, SHIVAMOGGA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institute',
            name='b_name',
            field=models.CharField(default='CANARA BANK', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institute',
            name='ifsc',
            field=models.CharField(default='CNRB0006322', max_length=20),
            preserve_default=False,
        ),
    ]
