# Generated by Django 4.0 on 2022-02-09 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_institute_ac_name_institute_ac_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='b_address',
        ),
    ]
